name: my_first_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 在flutter中使用webview https://www.jianshu.com/p/4aabe453eb26
  webview_flutter: ^0.3.10+4
  # json转 dart model类 https://book.flutterchina.club/chapter11/json_model.html
  json_annotation: ^2.0.0
  # 介绍shared_preferences https://www.jianshu.com/p/735b5684e900
  shared_preferences: ^0.4.2
  path_provider: ^0.5.0+1
  # 请求封装 https://book.flutterchina.club/chapter10/dio.html
  # https://pub.flutter-io.cn/packages/dio
  dio: ^3.0.8
  # 简单介绍，非官方文档 https://www.jianshu.com/p/7085019c4228
  # https://juejin.im/post/5d00a84fe51d455a2f22023f#heading-18
  # https://pub.flutter-io.cn/packages/provider
  provider: ^4.0.1
  # 简单介绍 https://juejin.im/post/5d051a5b6fb9a07ec07fbdc5
  fluro: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  # json转 dart model类 https://book.flutterchina.club/chapter11/json_model.html
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
